### ISSUE TITLE
Support to use OpenAI API key?

### ISSUE THREAD

**Issue by PeterDaveHello** [dtkdt100/Chat-GPT-for-Gmail#19]
With an API key, you won't need to pass Cloudflare security checks 🎉

**Comment by dtkdt100** [comment]
Hi @PeterDaveHello, there is support for an API key!

Check out release [1.0.4](https://github.com/dtkdt100/Chat-GPT-for-Gmail/releases/tag/v1.0.4). Make sure you are in the lastest version in chrome/firefox store.

In order to apply the api key to this extension:
1. open options page (by clicking the extension icon and tap "open options page")
2. choose "openAI API key"
3. enter your key
4. click save

**Comment by PeterDaveHello** [comment]
Turned out the version available on AMO ([addons.mozilla.org](http://addons.mozilla.org/)) is 1.0.3! Which is updated 2 months ago 🤣 

Would you like to update it? (Maybe use 1.0.5?)

**Comment by dtkdt100** [comment]
Oh, sorry my mistake! I probably upload it but forgot to submit it.

I will submit it now, and update you when it is up. 
Thanks for mentioning it!!

For now, if you want, you could download firefox.zip file in the latest release and use it.

**Comment by dtkdt100** [comment]
@PeterDaveHello 1.0.5 version is up!

**Comment by PeterDaveHello** [comment]
It's now asking for permission to access **My data for all websites**, is that really needed?

![image](https://user-images.githubusercontent.com/3691490/224370533-07491818-3f87-4310-8391-c6b4275aec48.png)

**Comment by dtkdt100** [comment]
I did it because a lot of users are complaining about the button not showing up, #15 .

I think I missed some url, mabye different gmail url in different countries, I followed [ChatGPT Writer - Write mail, messages with AI](https://chrome.google.com/webstore/detail/chatgpt-writer-write-mail/pdnenlnelpdomajfejgapbdpmjkfpjkp) manifest.

I understood that the `"host_permissions": ["https://*.openai.com/", "https://mail.google.com/*"],` is the websites that I am taking data from, but I was probably wrong, I will fix it. 

Thanks a lot
